### ISSUE TITLE
Add inherent field for the user who last updated the Organization element

### ISSUE THREAD

**Issue by dsmrt** [flipbox/organization#3]
It'd be nice to know who last updated the organization. Similar author on entries.

**Comment by nateiler** [comment]
I go back and forth on this...whether it should be part of this plugin or if it's better suited as an 'audit' plugin that this one integrates with.  Thinking element revisions without all the content.

Thinks to consider: Updates made through the CLI do not have an identity ... how to record those.

**Comment by dsmrt** [comment]
That makes sense I'll close this and we can reopen as needed.
